language: java

jdk:
  - openjdk8
  
branches:
  only:
  - master
  - development

before_script: 
  - ls -la
  
script: 
  - mvn clean package jacoco:report

after_success:
  - echo "Process terminated successfully."
